sudo: required
services:
    - docker

before_install:
    - docker build -t theautonater801/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true theautonater801/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: "frontend2"
    env: "Frontend2-env"
    bucket_name: "elasticbeanstalk-us-east-2-590183884677"
    bucket_path: "frontend2"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"
