sudo: required
services:
    - docker

before_install:
    - docker build -t theautonater801/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true theautonater801/docker-react npm run test